Dev
HACKONDEX/Python pull request #1
Opened 2020-04-17 10:18 UTC by HACKONDEX

Здравствуйте! 
Я старался по максимуму. 
У меня все запускается только через команду pyhton3 вместо ./ 
Еще не знаю как это исправлять.
Местами мой код просто ужасен, я не успевал находить более разумные методы и придумывать
алгоритмы по круче(

2020-04-17 14:23 UTC, WokinShopash commented
В режиме encode с заданием выходного файла, если файла нет (а это нормальная ситуация), то  шифрованный текст выводится в консоль, а не в файл

Пока мимо, исправляй

2020-04-17 22:41 UTC, HACKONDEX commented
Вроде исправил, как обычно говорят, у меня работает))

2020-04-26 12:07 UTC, WokinShopash requested changes

2020-04-26 12:07 UTC, WokinShopash commented on alphabet.py
> +alphabet = [lowercase, uppercase]
В конце файла по кодстайлу нужен перенос строки

2020-04-26 12:07 UTC, WokinShopash commented on alphabet.py
> +    dictionary['size'] = len(string_)
Во-первых, смешивать ключи в однородном словаре -- не очень хорошо, я бы разделил прямой и обратный словарь и тем более не стал бы помещать туда словаь

2020-04-26 12:07 UTC, WokinShopash commented on alphabet.py
> +    for i in range(len(string_)):
Тут лучше использовать enumerate

2020-04-26 12:07 UTC, WokinShopash commented on base_functionals.py
> +    if cipher == 'cesar':
Что-то с именем шифра тут не так

2020-04-26 12:07 UTC, WokinShopash commented on base_functionals.py
> +def hack_cesar(input_filename, output_filename, any_input_direction, any_output_direction, model_filename):
Давай не будем обижать старика Гая Юлия и напишем везде его имя правильно: Caesar

2020-04-26 12:07 UTC, WokinShopash commented on encryptor.py
> +# try:
Закомментированный код удалить

2020-04-26 12:07 UTC, WokinShopash commented on encryptor.py
> +except:
except без указания исключения  - это, конечно, очень хороший способ сделать непадающую программу, но все-таки, надо перехватывать конкретные, заранее понятные и ожидаемые исключения, и обрабатывать их не молча. Например, когда входного файла нет, вполне себе можно громко упасть (питон сам это прекрасно сделал бы, если бы ты не перехватил FileNotFoundError)

2020-04-26 12:07 UTC, WokinShopash commented on encryptor.py
> +    if not type(args.output_file) == type(None):
args.output_file is None

2020-04-26 12:07 UTC, WokinShopash commented on hack.py
> +        summary /= 26
Волшебная константа!

2020-04-26 12:07 UTC, WokinShopash commented on encryptor.py
> +if args.command == 'train':
В хорошем коде проверка args.command == X для каждого кода делается ровно один раз. Чтобы можно было легко в одном месте понять, что произойдет в том или ином случае

2020-04-26 12:07 UTC, WokinShopash commented on encryptor.py
> +commands = argparse.ArgumentParser()
При таком подходе в режимах будут пристутствовать незначащие аргументы, что приведет к запутыванию пользователя.
Лучше разобрать аргументы через subparsers

2020-04-28 18:36 UTC, HACKONDEX commented
Исправил все замечания, улучшил асимптотики, добавил subparser. Готов к второй волне)

2020-05-03 17:57 UTC, WokinShopash requested changes

2020-05-03 17:57 UTC, WokinShopash commented on alphabet.py
> +def built_alphabet(string_, mode):
Я понял, что ты тут хотел сделать, но у меня на это потребовалось чуть дольше времени, чем стоит.
Целочисленный аргумент используется достаточно странно, учитывая, что у него есть всего 2 значения, при которых все не упадет, логичнее сделать его bool'ом. 
Опять же, лучше назвать его как-то более явно (учитывая, что его назначение - указать, прямой или обратный алфавит)

2020-05-03 17:57 UTC, WokinShopash commented on alphabet.py
> +size = 26
Надо вычислить из других значений.

2020-05-03 17:57 UTC, WokinShopash commented on encryptor.py
> +    call_cipher(args, 'enc')
Не экономь на символах, читать гораздо лучше полные слова.
Учитывая, что тут всего 2 валидных значения, возможно, этот параметр должен быть bool

2020-05-03 17:57 UTC, WokinShopash commented on base_functionals.py
> +def hack_cesar(input_filename, output_filename, any_input_direction, any_output_direction, model_filename):
Кажется, все еще не исправлено

2020-05-03 17:57 UTC, WokinShopash commented on base_functionals.py
> +    create_output(output_filename, any_output_direction, output_string)
Зачем во всех внутренних функциях заводить праметры any_input_direction/any_output_direction и вызывать return_input/create_output, когда можно сделать это на шаг раньше в call_cipher?

2020-05-03 17:57 UTC, WokinShopash commented on encryptor.py
> +def input_file_checker(args_input_file, file_name):
Объедини эту функцию с return_input, они все равно друг с другом неразрывно связаны, а промежуточный результат никак иначе не используется

2020-05-03 17:57 UTC, WokinShopash commented on encryptor.py
> +parser_hack.add_argument('--cipher', choices=['caesar'], help=' type of cipher ', required=True)
Этого аргумента в условии не было

2020-05-03 17:57 UTC, WokinShopash commented on hack.py
> +def hack_cesar_from_string(input_string, model_filename):
Опять неправильно шифр назван

2020-05-03 17:57 UTC, WokinShopash commented on hack.py
> +    median = 100
Если считаешь среднее арифметическое, почему переменная называется median?

2020-05-03 17:57 UTC, WokinShopash commented on hack.py
> +            new_freq[j] = ordinary_frequency[alphabet.lowercase_dict[(alphabet.lowercase[j] + i) % alphabet.size]]
Зачем складывать, когда можно сразу подставлять это значение в следующем цикле на лету?

2020-05-03 17:57 UTC, WokinShopash commented on train.py
> +        frequency[i] = 0
Counter и так выставляет значения по умолчанию (как defaultdict), поэтому это не нужно

2020-05-03 17:57 UTC, WokinShopash commented on train.py
> +    freq = collections.Counter()
Counter используется обычно сразу конструируясь от объекта, например:
`freq = Counter("abacabda")`
Тут defaultdict достаточно

2020-05-03 17:57 UTC, WokinShopash commented on vigenere.py
> +def get_key_of_the_same_size(key, code_string):
Нет, не стоит так делать, зачем?
Если входной текст очень большой, то и наш супердлинный ключ выйдет большой.
Зачем удваивать затраты по памяти? Вычисляй текущую позицию в коротком ключе на лету

2020-05-03 17:57 UTC, WokinShopash commented on vigenere.py
> +        if code_string[i] in alphabet.lowercase:
Логика преобразования "(буква текста + сдвиг) -> закодированная буква" с перебором регистра и т.д. одинаковый у Цезаря и Виженера

2020-05-07 20:51 UTC, HACKONDEX commented
Здравствуйте! Вроде исправил все замечания, кода стала намного меньше)

2020-05-10 21:40 UTC, WokinShopash requested changes

2020-05-10 21:40 UTC, WokinShopash commented on hack.py
> +    median = 100
Ответа не вижу.

2020-05-10 21:40 UTC, WokinShopash commented on hack.py
> +def hack_cesar_from_string(input_string, model_filename):
Не исправлено.

2020-05-10 21:40 UTC, WokinShopash commented on encryptor.py
> +parser_hack.add_argument('--cipher', choices=['caesar'], help=' type of cipher ', required=True)
Не исправлено.

2020-05-13 15:23 UTC, WokinShopash requested changes

2020-05-13 15:23 UTC, WokinShopash commented on vigenere.py
> +    answer = ""
Зачем эта ненужная переменная?
Можно же сразу `"".join`

2020-05-13 15:23 UTC, WokinShopash commented on train.py
> +    freq = collections.Counter(string.ascii_lowercase)
Тут что-то странное.
Зачем вызывать Counter от всех букв(?)
После этой строки во freq будут единички

2020-05-13 15:23 UTC, WokinShopash commented on hack.py
> +    average_arithmetical = 100
float("inf")

2020-05-13 15:23 UTC, WokinShopash commented on hack.py
> +        summary /= alphabet.size
Зачем делить? Если на сравнение и ответ это не повлияет

2020-05-13 15:23 UTC, WokinShopash commented on encryptor.py
> +def input_file_checker(args_input_file, file_name):
Все еще актуально.

2020-05-14 13:09 UTC, HACKONDEX commented
Здравствуйте, на счет input_checker и return_input,  я их слил в get_input, а для модели оставил с информацией.

2020-05-14 18:09 UTC, WokinShopash commented
> Здравствуйте, на счет input_checker и return_input, я их слил в get_input, а для модели оставил с информацией.

Не очень понял, где для модели?
Если про train, то там эти две функции тоже идут подряд в точно такой же связке.
В hack аргумент model обязательный, и там эта функция не нужна, нужно просто прочитать или упасть, если файла нет.

2020-05-14 18:14 UTC, HACKONDEX commented
Ну вот, мой input_checker упадет если модели нет. А если есть то return_input не поможет потому что json файл по другому открывается.

2020-05-14 18:16 UTC, HACKONDEX commented
Или я должен при помощи декоратора все слить в единую функцию?

2020-05-14 18:29 UTC, WokinShopash commented
Ни то, ни другое.
Тут принцип простоты и несоздавания лишних сущностей говорит там, что нужно :
1. для всех обычных кейсов сделать простую, лаконичную функцию, которая принимает на вход filename, который потенциально придет из args, которая в случае наличия файла их читает, в случае отсутствия - читает input()
2. В той части hack, где мы читаем модель, читать ее в лоб, без функции выше ЛИБО читать модель той же функцией и использовать json.loads вместо json.load

2020-05-14 18:36 UTC, HACKONDEX commented
То есть в hack я проверяю есть ли файл модели и читаю его как json, а input_checker и return_input объединяю в одну функцию?

2020-05-16 19:31 UTC, HACKONDEX commented
Добрый вечер, вроде сделал как вы сказали)

2020-05-17 11:45 UTC, WokinShopash requested changes
Финишная прямая

2020-05-17 11:45 UTC, WokinShopash commented on encryptor.py
> +    (get_input(args.input_file, "input"), right_frequency))
Тут что-то с внешним видом... Правильно будет так:
```
 create_output(args.output_file, base_functionals.hack_caesar(
    get_input(args.input_file, "input"), right_frequency
))
```

2020-05-18 15:19 UTC, HACKONDEX commented
Здравствуйте, исправлено. Получается если переносить после запетой - норм, а с скобками не норм ?

2020-05-21 19:07 UTC, WokinShopash approved these changes
Зачтено

2021-03-17 17:45 UTC, merged