Again
HACKONDEX/Python pull request #2
Opened 2020-05-12 21:27 UTC by HACKONDEX

2020-05-13 06:19 UTC, tardis-forever commented
Добавь, пожалуйста, README с описанием согласованной темы и способом запуска программы / тестов

2020-05-13 08:08 UTC, HACKONDEX commented
Простите, что забыл, уже добавил)

2020-05-17 10:44 UTC, tardis-forever requested changes

2020-05-17 10:44 UTC, tardis-forever commented on Client_server/lib.py
> +            raise ValueError
Можно просто `raise`, чтобы последнее исключение пробросить

2020-05-17 10:44 UTC, tardis-forever commented on Client_server/lib.py
> +        return return_
`return temperature, moisture`

2020-05-17 10:44 UTC, tardis-forever commented on Client_server/main.py
> +    parser.add_argument('--port', default=8000, type= int)
Лишний пробел

2020-05-17 10:44 UTC, tardis-forever commented on Client_server/main.py
> +                stop_session()
Не проще тогда и функции в лист сложить?

2020-05-17 10:44 UTC, tardis-forever commented on Client_server/server_functions.py
> +    return True
Зачем?

2020-05-18 15:58 UTC, HACKONDEX commented on Client_server/server_functions.py
> +    return True
Мне была нужна функция которая вернет true если нет исключений в декораторе, сейчас попробую с лямбда функцией.

2020-05-19 11:08 UTC, tardis-forever requested changes

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/functions.py
> +    for i in city_list_:
`i` используется для индексов и числовых счетчиков

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/functions.py
> +    for i in city_list_:
Можно записать одной строкой

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/lib.py
> +            raise
А какое поведение увидеть пользователь в этом случае?

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/lib.py
> +        for i in self.statistics:
`for t, m in self.statistics`, только переменные не однобуквенные

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/lib.py
> +        moisture /= len(self.statistics) + 1
Чем это мотивировано?

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/lib.py
> +    difference = int(first_city.get_temperature_in_celsius()) - int(second_city.get_temperature_in_celsius())
Если знаете, что такое `@property`, то можно им воспользоваться, чтобы не приходилось постоянно вызывать функции

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/main.py
> +def stop_session(*args):
Для чего здесь аргументы?

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/main.py
> +def print_list(*args):
И здесь тоже

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/main.py
> +    for i in commands_list:
Однобуквенные переменные

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/main.py
> +            for i in range(11):
Здесь стоит использовать `.index`, или какую-нибудь другую функцию поиска числа в массиве

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/server_functions.py
> +    return return_.join(temperatures)
Введение переменной здесь лишнее

2020-05-19 11:08 UTC, tardis-forever commented on Client_server/server_main.py
> +            (lambda: True)() and \
Не совсем понимаю: лямбда создается и тут же вызывается? Для чего это?

2020-05-19 20:48 UTC, HACKONDEX commented on Client_server/lib.py
> +            raise
Вы сказали использовать просто raise и я походу не совсем понял о чем вы.

2020-05-19 20:53 UTC, HACKONDEX commented on Client_server/server_main.py
> +            (lambda: True)() and \
Мой декоратор принимает функцию которую, выполняет если город присутствует в списке обслуживаемых, через функцию return_true я понимал есть ли оба города в списке и считал разницу их температур. Поменял return_true на лямбда функции.

2020-05-19 20:58 UTC, HACKONDEX commented on Client_server/lib.py
> +        moisture /= len(self.statistics) + 1
Ну мы сами выбирали, что писать вот я и написал. Как предсказание погоды беру среднее арифметическое собранных данных)

2020-05-19 21:01 UTC, HACKONDEX commented on Client_server/main.py
> +def print_list(*args):
Я в функции в форе перебора команд передаю args, и если тут убрать *args то она падает с еррором что не ждал аргументов но получил.

2020-05-20 11:09 UTC, tardis-forever commented on Client_server/lib.py
> +        moisture /= len(self.statistics) + 1
ок

2020-05-20 11:11 UTC, tardis-forever commented on Client_server/server_main.py
> +            (lambda: True)() and \
А  вызывать ее здесь зачем?

2020-05-20 19:33 UTC, HACKONDEX commented on Client_server/lib.py
> +            raise
Я если честно не понял как надо тут делать, чтобы два раза except не писать.

2020-05-20 20:01 UTC, HACKONDEX commented on Client_server/server_main.py
> +            (lambda: True)() and \
Туда надо передавать, что то callable, что вернет True, и кроме лямбда функции и моей return_true я не нашел вариантов (

2020-05-22 11:54 UTC, tardis-forever commented on Client_server/server_main.py
> +            (lambda: True)() and \
Еще раз, если туда надо передать callable, который вернет `True`, то это просто `lambda : True`. Но то, что написано здесь - вызов этого callable, `(lambda : True)() == True`

2020-05-22 12:03 UTC, tardis-forever requested changes
Все строки вынести в отдельный файл, все числовые константы явно объявить

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/functions.py
> +city_name_message = "Enter city name> "
Лучше вообще все текстовые данные вынести в отдельный файл с конфигурацием (условно, если это большой серьезный проект, то при локализации на другой язык проще переводит все строки разом)

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/functions.py
> +    for i in city_list_:
Почему замечания не исправлены?

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/functions.py
> +    verdict = requests.get(f'http://{args.host}:{args.port}/temperature',
`f'http://{args.host}:{args.port}/` везде дублируется

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/functions.py
> +    verdict = requests.get(f'http://{args.host}:{args.port}/moisture',
И все handle (/temperature, /moisture) надо вынести в одно место, чтобы в сервере и в клиенте использовалась одна и та же константа

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/lib.py
> +            raise
Ну в общем, программа при введении некорректных данных упадет или нет? И какое поведение ожидается автором кода в этом случае?

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/lib.py
> +        return self.temperature + 273
Константа

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/lib.py
> +        return int(self.temperature * (9 / 5) + 32)
Константы

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/lib.py
> +        return_[7] = str(-difference)
Можно ветвление вставить внутрь создания листа с помощью тернарного оператора

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/main.py
> +    parser.add_argument('--port', default=8000, type=int)
Константа

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/main.py
> +    print("Type \'help\' for command list")
Одинарные кавычки внутри двойных не надо экранировать

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/main.py
> +                print("Unknown command, please try again!")
Текстовые константы

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/server_functions.py
> +               "degrees by Celsius.", "Moisture level will be", str(int(data[1]))]
Для этого проще использовать форматную строку. (и в случае выше с разницой температур тоже)

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/server_main.py
> +    application.run('::', port=8000, debug=True)
Константа

2020-05-22 12:03 UTC, tardis-forever commented on Client_server/server_main.py
> +main()
Лучше это оборачивать в `if __name__ == __main__`

2020-05-22 12:15 UTC, HACKONDEX commented on Client_server/functions.py
> +    verdict = requests.get(f'http://{args.host}:{args.port}/temperature',
Ой, я случайно его пропустил. Вроде понял как исправить.

2020-05-22 12:15 UTC, HACKONDEX commented on Client_server/functions.py
> +    verdict = requests.get(f'http://{args.host}:{args.port}/moisture',
Понял, исправлю.

2020-05-22 12:15 UTC, HACKONDEX commented on Client_server/lib.py
> +        return self.temperature + 273
До этого когда падала я ловил и все было хорошо, а потом вы сказали поменять и я до сих пор не понял что надо делать.
Это же формула температуры. Она и в Африке будет 273, зачем заводить переменную?)

2020-05-22 12:18 UTC, HACKONDEX commented on Client_server/lib.py
> +        return_[7] = str(-difference)
А я и не знал, что есть тернарный оператор, исправлю.

2020-05-22 12:20 UTC, HACKONDEX commented on Client_server/server_main.py
> +main()
А тут нет проблем если модуль называется server_main, просто я так пытался и не сработало

2020-05-22 12:33 UTC, HACKONDEX commented on Client_server/server_main.py
> +            (lambda: True)() and \
В первой скобке надо написать функцию а в второй аргументы которые она принимает, я пробовал убирать вторые скобки но тогда она падает( 
Но вроде все работает, там вызова True не получаю когда город не из списка.

2020-05-22 12:38 UTC, tardis-forever commented on Client_server/server_main.py
> +main()
Ну а в чем проблема тогда нужное имя модуля тут поставить?

2020-05-22 12:39 UTC, tardis-forever commented on Client_server/server_main.py
> +main()
Достаточно сделать `print(__name__)`, чтобы узнать, какое имя

2020-05-22 12:40 UTC, tardis-forever commented on Client_server/server_main.py
> +            (lambda: True)() and \
О, я кажется поняла в итоге структуру кода

2020-05-22 12:41 UTC, tardis-forever commented on Client_server/server_main.py
> +            (lambda: True)() and \
Нет никаких способов упростить конструкцию? Она очень нечитаемая

2020-05-22 14:45 UTC, HACKONDEX commented on Client_server/server_main.py
> +            (lambda: True)() and \
Ну пожалуйста, я и так уйму времени потратил чтобы убрать дублирование, до этого сложного декоратора там везде были 6 одинаковых строчек, сейчас это длинные вызовы)

2020-05-22 15:14 UTC, HACKONDEX commented
Я исправил проблему с args, добавил много констант. Возник вопрос стоит ли выносить строки которые один раз используются, если да можно ли вместо 
return_ = [ const_string1, const_string2, .....]
return "".join(return_) 
использовать
return const_string1 + const_string2 + .....

2020-05-22 15:50 UTC, HACKONDEX commented
Все ручные строки положил в constatns.py. Жду новых замечаний)

2020-05-22 21:23 UTC, tardis-forever requested changes

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/functions.py
> +        input_ = input(cs.stop_session_print[0])
Лучше либо не list, а dict, чтобы можно было взять `['start_msg']`, например, либо 3 отдельные константы

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/functions.py
> +        elif input_ == 'N' or input_ == 'n':
`input_ in ['N', 'n']`, и лист можно тоже в конфиг

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/lib.py
> +            raise ValueError
(так сохранится traceback)

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/lib.py
> +            raise ValueError
Или ловить как 
```python
except ValueError as e:
    ...
    raise ... from e
```

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/lib.py
> +        return int(self.temperature * (coefficients[0] / coefficients[1]) + coefficients[2])
Можно функцию перевода положить в конфиг

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Это стоит сделать методом city

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Например, можно переопределить `__str__` или `__repr__`

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/server_functions.py
> +        return_.append("\n")
Это стоит тоже вынести в функцию / метод

2020-05-22 21:23 UTC, tardis-forever commented on Client_server/server_functions.py
> +    return_ = list()
`[]`

2020-05-22 21:33 UTC, HACKONDEX commented on Client_server/lib.py
> +        return int(self.temperature * (coefficients[0] / coefficients[1]) + coefficients[2])
Я не понял что такое конфиг, вы имеете введу сделать отдельную функцию снаружи?

2020-05-22 21:35 UTC, HACKONDEX commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Если честно вообще не понял о чем вы.
Насколько я понял можно сделать функцию которая вернет лист с тремя температурами?

2020-05-22 21:37 UTC, HACKONDEX commented on Client_server/server_functions.py
> +        return_.append("\n")
То есть написать функцию f(args*) которая вернет list из аргументов, и потом ее везде юзать?

2020-05-22 21:38 UTC, tardis-forever commented on Client_server/lib.py
> +        return int(self.temperature * (coefficients[0] / coefficients[1]) + coefficients[2])
Конфиг - тот файл, где все константы сейчас лежат

2020-05-22 21:39 UTC, tardis-forever commented on Client_server/lib.py
> +        return int(self.temperature * (coefficients[0] / coefficients[1]) + coefficients[2])
И там уже, наверное, можно 9 и 5 использовать, но строго внутри этой функции

2020-05-22 21:40 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Можно сделать функцию, которая возьмет city (`city_dict[name]`) и по нему вернет итоговую строку (результат `"".join(temperatures )`

2020-05-22 21:41 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Потому что здесь привязки ко всему `city_dict` нет, только к конкретному городу

2020-05-22 21:42 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
А если теперь это будет только от конкретного города зависеть, можно вынести это в метод класса `City`

2020-05-22 21:42 UTC, tardis-forever commented on Client_server/server_functions.py
> +        cs.kelvin, str(city_dict[name].get_temperature_in_kelvins())]
Например, можно переопределить `__str__`, и тогда такая информация будет выдаваться, если сделать `str(city)`

2020-05-22 21:44 UTC, HACKONDEX commented
Спасибо, вроде понял, завтра исправлю все. Постараюсь)

2020-05-22 21:45 UTC, tardis-forever commented on Client_server/server_functions.py
> +        return_.append("\n")
Ну в данном случае можно сузить функциональность, и написать функцию, которая берет (например) `i`, `data[i]` и выдает строку, собранную из 6, которые в `appaend`'ах

2020-05-22 21:47 UTC, tardis-forever commented
Там еще в обработке исключительных ситуаций осталась строковая константа

2020-05-23 09:50 UTC, HACKONDEX commented
Вроде нечего не упустил)

2020-05-23 10:15 UTC, tardis-forever requested changes

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/functions.py
> +        print(command_name)
Всю эту фнкцию можно заменить на `print(*cs.commands_list, sep='\n')`

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/server_functions.py
> +    return "".join(temperatures)
Не лучше это было все-таки методом `City` сделать?

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/server_functions.py
> +def make_statistics_list(result_list, data, day):
И это? И возвращать можно все-таки строчку тогда

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/server_main.py
> +
2 пустые строки

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/server_main.py
> +city_dict = {city_list[0]: lib.City(city_list[0], 15, 70), city_list[1]: lib.City(city_list[1], 20, 40)}
Возможно, тоже лучше в константы положить

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/tests.py
> +        self.assertEqual(havana.get_temperature_in_kelvins(), havana.get_temperature_in_celsius() + 273)
Здесь можно использовать функцию перевода C -> K из constants

2020-05-23 10:15 UTC, tardis-forever commented on Client_server/functions.py
> +            print(cs.stop_session_print4)
Надо либо чуть более говорящие названия дать этим константам, либо все-таки dict (`cs.stop_session['first_question'], cs.stop_session['goodbye']`, например)

2020-05-23 22:10 UTC, HACKONDEX commented on Client_server/server_main.py
> +city_dict = {city_list[0]: lib.City(city_list[0], 15, 70), city_list[1]: lib.City(city_list[1], 20, 40)}
Я так пробовал но тогда будет цикл между lib, constants и server_main, если выносить то в отдельный файл, сделать в отдельном?

2020-05-23 22:23 UTC, HACKONDEX commented
Простите что так поздно, делал лабу)
Так как коментов очень много, очень вероятно, что я что-то пропустил.

2020-05-24 10:09 UTC, tardis-forever commented on Client_server/server_main.py
> +city_dict = {city_list[0]: lib.City(city_list[0], 15, 70), city_list[1]: lib.City(city_list[1], 20, 40)}
Например, можно так, да

2020-05-24 10:11 UTC, tardis-forever commented
Надо дефолтные города все-таки куда-то вынести. Больше исправлений, думаю, не понадобится. Я правильно понимаю, что бонусных баллов тут нет?

2020-05-24 10:34 UTC, HACKONDEX commented
Да бонусов нет(

2020-05-24 10:50 UTC, tardis-forever commented
Зачтено

2020-05-24 10:51 UTC, merged